const SHOW_BOILER_TYPES = 'SHOW_BOILER_TYPES';
const SHOW_BOILER_TYPES_SUCCED = 'SHOW_BOILER_TYPES_SUCCED';
const SHOW_BOILER_TYPES_FAILED = 'SHOW_BOILER_TYPES_FAILED';

const CREATE_BOILER_TYPE = 'CREATE_BOILER_TYPE';
const CREATE_BOILER_TYPE_SUCCED = 'CREATE_BOILER_TYPE_SUCCED';
const CREATE_BOILER_TYPE_FAILED = 'CREATE_BOILER_TYPE_FAILED';

const DELETE_BOILER_TYPE = 'DELETE_BOILER_TYPE';
const DELETE_BOILER_TYPE_SUCCED = 'DELETE_BOILER_TYPE_SUCCED';
const DELETE_BOILER_TYPE_FAILED = 'DELETE_BOILER_TYPE_FAILED';

const UPDATE_BOILER_TYPE = 'UPDATE_BOILER_TYPE';
const UPDATE_BOILER_TYPE_SUCCED = 'UPDATE_BOILER_TYPE_SUCCED';
const UPDATE_BOILER_TYPE_FAILED = 'UPDATE_BOILER_TYPE_FAILED';

export {
  SHOW_BOILER_TYPES,
  SHOW_BOILER_TYPES_SUCCED,
  SHOW_BOILER_TYPES_FAILED,
  CREATE_BOILER_TYPE,
  CREATE_BOILER_TYPE_SUCCED,
  CREATE_BOILER_TYPE_FAILED,
  DELETE_BOILER_TYPE,
  DELETE_BOILER_TYPE_SUCCED,
  DELETE_BOILER_TYPE_FAILED,
  UPDATE_BOILER_TYPE,
  UPDATE_BOILER_TYPE_SUCCED,
  UPDATE_BOILER_TYPE_FAILED,
};
