const SHOW_BOILER_TYPES = 'SHOW_BOILER_TYPES';
const SHOW_BOILER_TYPES_SUCCED = 'SHOW_BOILER_TYPES_SUCCED';
const SHOW_BOILER_TYPES_FAILED = 'SHOW_BOILER_TYPES_FAILED';

const DELETE_BOILER_TYPE = 'DELETE_BOILER_TYPE';

export {
  SHOW_BOILER_TYPES,
  SHOW_BOILER_TYPES_SUCCED,
  SHOW_BOILER_TYPES_FAILED,
  DELETE_BOILER_TYPE,
};
